# Generated by Django 3.1.2 on 2021-07-31 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('profile_img', models.ImageField(blank=True, upload_to='pro_img')),
                ('dob', models.DateField()),
                ('mobile_no', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('West Bengal', 'West Bengal'), ('Delhi', 'Delhi'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Tamil Nadu', 'Tamil Nadu'), ('Bihar', 'Bihar'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala')], max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('college_name', models.TextField()),
                ('school_name', models.TextField()),
                ('class_12', models.FloatField()),
                ('class_10', models.FloatField()),
                ('persue_course', models.CharField(choices=[('Bachelor of Technology', 'Bachelor of Technology'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bacheor of Science', 'Bachelor of Science'), ('Bachelor of Commerce', 'Batchelor of Commerce')], max_length=150)),
                ('language', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('intern_exp', models.TextField(blank=True)),
                ('facebook', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('linkedIn', models.CharField(max_length=150)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
        ),
    ]
