# Generated by Django 3.1.2 on 2021-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
